---
- name: Configure Node Exporter on Solana Validator
  hosts: all # Or specify your target hosts group
  become: true # Most tasks require sudo
  vars_files:
    - vars/main.yml # Or specific vars file like vars/testnet.yml

  pre_tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600 # One hour
      when: ansible_os_family == "Debian"
      changed_when: false # This task should not report a change

  roles:
    - node_exporter_config
